- platform: min_max
  name: "House Average Temperature"
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.living_room_sensor_temperature
    - sensor.office_sensor_temperature
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_temperature
    - sensor.gigaplex_nas_temp

- platform: integration
  source: sensor.gigaplex_switch_power
  name: Gigaplex Switch Energy
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.office_desk_power
  name: Office Desk Energy
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.printer_3d_power
  name: 3D Printer Energy
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.fridge_switch_power
  name: Fridge Switch Energy
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.washing_machine_switch_power
  name: Washing Machine Switch Energy
  unit_prefix: k
  round: 2
  method: left
