services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${CONFIG}/plex:/config
      - ${ROOT}/gigaplex-tv:/tv #TV Shows
      - ${ROOT}/gigaplex-movies:/movies #Movies
    restart: unless-stopped
#PlexTraktSync
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - ${CONFIG}/plextraktsync/config:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#PlexTraktSync Watch
  plextraktsyncwatch:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsyncwatch
    volumes:
      - ${CONFIG}/plextraktsync/config:/app/config
    command: watch
    restart: always
#Scheduler PlexTraktSync
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 6h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"

#Tautulli
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

# Kometa - Plex Meta Manager
  kometa:
    image: kometateam/kometa
    container_name: kometa
    environment:
      - TZ=${TZ} #optional
    volumes:
      - ${CONFIG}/kometa/config:/config
    restart: unless-stopped