services:
#Homepage
#Local instance
  homepage_local:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage_local
    environment:
      PUID: ${PUID} # optional, your user id
      PGID: ${PGID} # optional, your group id
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.50:3030
      TZ: ${TZ}
    ports:
      - 3030:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped