services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    ports:
      - 6881:6881
      - 6881:6881/udp
      #- 8000:8000/tcp
      #- 9696:9696 #Prowlarr
      #- 7878:7878 #Radarr
      #- 8989:8989 #Sonarr
      #- 8191:8191 #FlareSolver

      #- 8888:8888/tcp # HTTP proxy Remove if not using
      #- 8388:8388/tcp # Shadowsocks Remove if not using
      #- 8388:8388/udp # Shadowsocks Remove if not using

      #QBittorrent ports
      #- 8080:8080
      - 8081:8081
    volumes:
      - ${CONFIG}/gluetun:/gluetun
    environment:
      #- HTTPPROXY=on #Remove if not using for HTTP proxy
      #- SHADOWSOCKS=on #Remove if not using for Shadowsocks Proxy
      - TZ=Africa/Lagos
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=uDY6swdO4iRaQ0R/QgwjS7z9rWBW7ZbTBjZQWqCrMmk=
      - WIREGUARD_PRESHARED_KEY=kVlvZ2QNG2uincaHt/GktHeEMF+yh8JvZjyJ3PVR2Iw=
      - WIREGUARD_ADDRESSES=10.130.205.211/32