---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Service Status:
    - Github:
        - abbr: GH
          href: https://github.com/salakoayoola