services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      # - 443:443/tcp # Uncomment if you want HTTP3
      # - 443:443/udp # Uncomment if you want HTTP3
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    env_file: .env # use .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      # - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.${DOMAIN}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.${DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  goaccess:
    image: justsky/goaccess-for-nginxproxymanager:latest
    container_name: goaccess-traefik
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    volumes:
      - ./data/logs:/opt/log
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goaccess.entrypoints=http"
      - "traefik.http.routers.goaccess.rule=Host(`goaccess.${DOMAIN}`)"
      - "traefik.http.routers.goaccess.middlewares=traefik-https-redirect"
      - "traefik.http.routers.goaccess-secure.entrypoints=https"
      - "traefik.http.routers.goaccess-secure.rule=Host(`goaccess.${DOMAIN}`)"
      - "traefik.http.routers.goaccess-secure.tls=true"
      - "traefik.http.routers.goaccess-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.goaccess.loadbalancer.server.port=7880"

networks:
  proxy:
    external: true
